# Generated by Django 5.1.1 on 2024-09-26 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('sending_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('sms_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Yuborildi'), ('error', 'Rad etildi')], default='pending', max_length=10)),
                ('user_status', models.CharField(choices=[('active', 'Davolanmoqda'), ('deactive', "Davolanib bo'lgan")], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
