# Generated by Django 5.1.1 on 2024-09-26 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sms_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Yuborildi'), ('error', 'Rad etildi')], default='pending', max_length=10)),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='smsAPI.usermessage')),
            ],
        ),
    ]
